steps:
  - label: "Hello"
    key: echo-hello
    command: "echo 'Hello from bash'"

  - wait

  - label: "Create & Upload Docker Image to AWS/ECR"
    key: create-and-upload-docker-image
    command: "sh ./scripts/upload-docker-image.sh"

  - label: "Run Docker Python script"
    key: run-docker-python-script
    command: "docker run buildkite-getting-started-image:latest"
    depends_on:
      - create-and-upload-docker-image

  - label: ":hammer: Example Script"
    key: example-script
    command: "sh ./scripts/script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    depends_on:
      - create-and-upload-docker-image
      - run-docker-python-script

  - label: ":terraform: Trigger Pipelines"
    plugins:
      - chronotc/monorepo-diff#v2.3.0:
          diff: git diff --name-only HEAD~1
          watch:
            - path:
                - ".buildkite"
                - "terraform/foo"
              config:
                trigger: "buildkite-getting-started-terraform"
                label: "Terraform foo project"
                build:
                  message: ":terraform: foo"
                  env:
                    - TERRAFORM_DIR=terraform/foo
            - path:
                - ".buildkite"
                - "terraform/bar"
              config:
                trigger: "buildkite-getting-started-terraform"
                label: "Terraform bar project"
                build:
                  message: ":terraform: bar"
                  env:
                    - TERRAFORM_DIR=terraform/bar
